  1 .PHONY:all
  2 
  3 all:server client
  4 
  5 server:serverPipe.c
  6     gcc -o $@ $^
  7 
  8 client:clientPipe.c
  9     gcc -o $@ $^
 10 
 11 .PHONY:clean
 12 
 13 clean:
 14     rm -f client server                                                                                                                                  
~                                                                                                                                                            
~                                                                                                                                                            
~                                    
